name: Example env
on: [push]
jobs:
  job_with_my_sql:
    runs-on: ubuntu-20.04
    environment: dev
      
    env: 
        MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
        MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}
        MYSQL_USER: ${{secrets.MYSQL_USER}}
        MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
        NEW_DATABASE: ${{secrets.NEW_DATABASE}}
    services:
      db:
        image: mysql:8.0
        ports: 
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{env.MYSQL_ROOT_PASSWORD}}
          MYSQL_DATABASE: ${{env.MYSQL_DATABASE}}
          MYSQL_USER: ${{env.MYSQL_USER}}
          MYSQL_PASSWORD: ${{env.MYSQL_PASSWORD}}
          NEW_DATABASE: ${{env.NEW_DATABASE}}
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: show docker containers
        run: docker ps -a
      - name: wait for MYSQL to be ready
        run: |
          echo "waiting for mysql to be ready"
          for i in {1..30}; do
            mysqladmin --protocol=tcp -h localhost -P 3306 -u root -p${{ env.MYSQL_ROOT_PASSWORD }} ping &> /dev/null && break
            echo "mysql is not ready yet...retrying in 2 seconds"
            sleep 2
          done
      - name: Create Database and Grant Full Permissions to User1
        run: |
          mysql --protocol=tcp -h localhost -P 3306 -u root -p${{ env.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${NEW_DATABASE};"
          mysql --protocol=tcp -h localhost -P 3306 -u root -p${{ env.MYSQL_ROOT_PASSWORD }} -e "CREATE USER IF NOT EXISTS '${{ env.MYSQL_USER }}'@'%' IDENTIFIED BY '${{ env.MYSQL_PASSWORD }}';"
          mysql --protocol=tcp -h localhost -P 3306 -u root -p${{ env.MYSQL_ROOT_PASSWORD }} -e "GRANT ALL PRIVILEGES ON ${NEW_DATABASE}.* TO '${{ env.MYSQL_USER }}'@'%'; FLUSH PRIVILEGES;"
      - name: Create Table and Insert Data
        run: |
          mysql --protocol=tcp -h localhost -P 3306 -u ${{ env.MYSQL_USER }} -p${{ env.MYSQL_PASSWORD }} ${NEW_DATABASE} -e "CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50));"
          mysql --protocol=tcp -h localhost -P 3306 -u ${{ env.MYSQL_USER }} -p${{ env.MYSQL_PASSWORD }} ${NEW_DATABASE} -e "INSERT INTO users (name) VALUES ('Alice'), ('Bob');"
      - name: Query Data
        run: |
          mysql --protocol=tcp -h localhost -P 3306 -u ${{ env.MYSQL_USER }} -p${{ env.MYSQL_PASSWORD }} ${NEW_DATABASE} -e "SELECT * FROM users;"
      
